FROM apache/airflow:2.7.3

USER airflow

ARG AIRFLOW_VERSION=2.7.3
ARG PYTHON_VERSION=3.8

RUN pip install --no-cache-dir \
  "openmetadata-ingestion[airflow]==1.11.2" \
  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN airflow version
