FROM apache/airflow:2.7.3

USER airflow

RUN pip install --no-cache-dir \
  "openmetadata-ingestion[airflow]==1.11.2" \
  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.8.txt"

RUN airflow version
